frontend/models/Task.php
<?php

namespace frontend\models;
use yii\db\Query;


use Yii;

/**
 * This is the model class for table "task".
 *
 * @property int $task_id
 * @property int $case_id
 * @property int $practice_id
 * @property string $case_manager
 * @property string $request_received_on
 * @property int $no_of_pages
 * @property int $revised_pages
 * @property string $assigned_to
 * @property string $note
 * @property string $assigned_on
 * @property string $reviewer
 * @property string $review_assigned_on
 * @property string $review_done
 * @property string $review_done_on
 * @property string $send_for_review
 * @property string $recode_sent_to
 * @property string $recode_sent_on
 * @property string $send_for_recode
 * @property string $close
 * @property string $closed_date
 * @property string $unplanned
 * @property string $sdlc_phase
 * @property string $type_of_request
 * @property string $file_type
 * @property string $estimated_time
 * @property string $development_time
 * @property string $review_time
 */
class Task extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'task';
    }
	
	public function getRole(){
		$query= new Query();
		$data= $query->SELECT(['role'])
					->FROM('user')
					//->where (['id' => Yii::$app->user->identity->getId()])
					->all();
		$b =\yii\helpers\ArrayHelper::map($data, 'role', 'role');
		return $data;
	}
	
	public function getListAssignedTo(){
		//$test=['user1'=>'user1', 'user2'=>'user2'];
		//$connection= \Yii::$app->db;
		//$model = $connection->createCommand('SELECT username FROM user');
		//$users = $model->queryAll();
		$query= new Query();
		$data= $query->SELECT(['username'])
					->FROM('user')
					->all();
		$b= \yii\helpers\ArrayHelper::map($data, 'username', 'username');
		
		echo "<pre>";
		//print_r ($b);
		echo "</pre>";
		return $b;
	}
	public function getReviewer(){
		$query= new Query();
		$data= $query->SELECT(['username'])
					->FROM('user')
					->all();
		$b =\yii\helpers\ArrayHelper::map($data, 'username', 'username');
		return $b;
	}
	
	public function getFileType(){
		$query= new Query();
		$data= $query->SELECT(['file'])
					->FROM('file_type')
					->all();
		$b =\yii\helpers\ArrayHelper::map($data, 'file', 'file');
		return $b;
	}
	
	public function getAssigned(){
		$query= new Query();
		$data= $query->SELECT(['task_id'])
					->FROM('task')
					->all();
		$b =\yii\helpers\ArrayHelper::map($data, 'task_id', 'task_id');
		return $b;
	}
	
	public function getSDLCPhase(){
		$query= new Query();
		$data= $query->SELECT(['phase'])
					->FROM('sdlc_phase')
					->all();
		$b =\yii\helpers\ArrayHelper::map($data, 'phase', 'phase');
		return $b;
	}
	
	
	public function getDataGraph1(){
		$query= new Query();
		
		$data= $query->SELECT(['type_of_request',"count(task_id) as cases_closed","sum(no_of_pages) as pages_closed"])
					->from('task')
					->where("close='yes'")
					->groupby('type_of_request')
					->all();
		
		
		//$b =\yii\helpers\ArrayHelper::index($data, 'type_of_request');
		
		
		echo "<pre>";
		//print_r ($b);
		//print_r ($data);
		echo "</pre>";
		//exit();
		return $data;
	}
	public function getleaderboard(){
		$query= new Query();
		
		$data= $query->SELECT(['assigned_to','concat(firstname," ",lastname) as userfullname',"count(task_id) as count","sum(no_of_pages) as pages"])
					->from('task')
                                        ->leftJoin('user','user.username = task.assigned_to')    
					->where("close='no'")
					->groupby('assigned_to')
					->all();
		return $data;
	}				
	public function getCountTotalTask() 
        {
                $query = new Query();

                return $query->SELECT(['count(task_id) as total_task'])
                                ->from('task')
                                ->scalar();
        }
        
        public function getTotalCloseTask() 
        {
                $query = new Query();

                return $query->SELECT(['count(task_id) as close_task'])
                                ->from('task')
                                ->where("close='yes'")
                                ->scalar();
        }
        
         public function getTotalOpenTask() 
        {
                $query = new Query();

                return $query->SELECT(['count(task_id) as open_task'])
                                ->from('task')
                                ->where("close='no'")
                                ->scalar();
        }
         public function getTotalPagesCoded() 
        {
                $query = new Query();

                return $query->SELECT(['sum(no_of_pages) as pages_closed'])
                               ->from('task')
                                ->where("close='yes'")
                                ->scalar();
        }
    public function getTypeOfRequest(){
		$query= new Query();
		$data= $query->SELECT(['request'])
					->FROM('type_of_request')
					->all();
		$b =\yii\helpers\ArrayHelper::map($data, 'request', 'request');
		return $b;
	}
	
	//public function getInReview
	
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['case_id'], 'required'],
			 [['case_id'], 'unique'],
            [['case_id', 'practice_id', 'no_of_pages', 'revised_pages'], 'integer'],
            [['request_received_on', 'assigned_on', 'review_assigned_on', 'review_done_on', 'recode_sent_on', 'closed_date'], 'safe'],
            [['estimated_time', 'development_time', 'review_time'], 'number'],
            [['case_manager', 'assigned_to', 'note', 'reviewer', 'send_for_review', 'recode_sent_to'], 'string', 'max' => 50],
            [['review_done', 'send_for_recode', 'close', 'unplanned', 'sdlc_phase', 'file_type'], 'string', 'max' => 10],
            [['type_of_request'], 'string', 'max' => 25],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'task_id' => 'Task ID',
            'case_id' => 'Case ID',
            'practice_id' => 'Practice ID',
            'case_manager' => 'Case Manager',
            'request_received_on' => 'Request Received On',
            'no_of_pages' => 'No Of Pages',
            'revised_pages' => 'Revised Pages',
            'assigned_to' => 'Assigned To',
            'note' => 'Note',
            'assigned_on' => 'Assigned On',
            'reviewer' => 'Reviewer',
            'review_assigned_on' => 'Review Assigned On',
            'review_done' => 'Review Done',
            'review_done_on' => 'Review Done On',
            'send_for_review' => 'Send For Review',
            'recode_sent_to' => 'Recode Sent To',
            'recode_sent_on' => 'Recode Sent On',
            'send_for_recode' => 'Send For Recode',
            'close' => 'Close',
            'closed_date' => 'Closed Date',
            'unplanned' => 'Unplanned',
            'sdlc_phase' => 'Sdlc Phase',
            'type_of_request' => 'Type Of Request',
            'file_type' => 'File Type',
            'estimated_time' => 'Estimated Time',
            'development_time' => 'Development Time',
            'review_time' => 'Review Time',
        ];
    }
}

frontend/controllers/TaskController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Task;
use frontend\models\TaskSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
//use yii\filters\AccessControl;
use yii\helpers\Html;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [

		   'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Task models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model= new Task();
		$searchModel = new TaskSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		$a= $model->getRole();
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider, 'role'=>$a
        ]);
    }

    /**
     * Displays a single Task model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new Task();
		$a= $model->getListAssignedTo();
		$b= $model->getReviewer();
		$c= $model->getSDLCPhase();
		$d= $model->getTypeOfRequest();
		$e= $model->getAssigned();
		return $this->render('view', [
            'model' => $this->findModel($id),'ListAssignedTo'=>$a,'Reviewer'=>$b , 'ListOfSDLCPhase'=>$c, 'TypeOfRequest'=>$d, 'Assigned'=>$e
        ]);
    }

    /**
     * Creates a new Task model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new Task();

        if ($model->load(Yii::$app->request->post())) {
			$model->sdlc_phase= '';



			if($model->save()){
				return $this->redirect(['view', 'id' => $model->task_id]);
			}

        }
		$a= $model->getFileType();
		$b= $model->getReviewer();
		$c= $model->getSDLCPhase();
		$d= $model->getTypeOfRequest();
        return $this->render('create', [
            'model' => $model,   'Reviewer'=>$b, 'ListOfSDLCPhase'=>$c, 'TypeOfRequest'=>$d, 'FileType'=>$a
        ]
		);
    }

    /**
     * Updates an existing Task model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->task_id]);
        }
		$a= $model->getListAssignedTo();
		$b= $model->getReviewer();
		$c= $model->getSDLCPhase();
		$d= $model->getTypeOfRequest();
		$e= $model->getAssigned();
		$f= $model->getFileType();
        return $this->render('update', [
            'model' => $model, 'ListAssignedTo'=>$a,'Reviewer'=>$b , 'ListOfSDLCPhase'=>$c, 'TypeOfRequest'=>$d, 'Assigned'=>$e, 'FileType'=>$f
        ]);
    }

    /**
     * Deletes an existing Task model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

	 public function actionSendForReview($id)
    {
             if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
             $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
			       $model->sdlc_phase= 'Review';



			if($model->save()){
				return $this->redirect(['view', 'id' => $model->task_id]);
			}

        }
		$a= $model->getListAssignedTo();
		$c= $model->getSDLCPhase();
		$d= $model->getTypeOfRequest();
        return $this->render('send-for-review', [
            'model' => $model,'ListAssignedTo'=>$a, 'ListOfSDLCPhase'=>$c, 'TypeOfRequest'=>$d
        ]);
    }

	public function actionSendForRecode($id)
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
            $model = $this->findModel($id);


        if ($model->load(Yii::$app->request->post())) {
			$model->sdlc_phase= 'Recode';
			$model->review_done='yes';

			if($model->save()){
				return $this->redirect(['view', 'id' => $model->task_id]);
			}

        }
		$a= $model->getListAssignedTo();
		$c= $model->getSDLCPhase();
		$d= $model->getTypeOfRequest();
        return $this->render('send-for-recode', [
            'model' => $model,'ListAssignedTo'=>$a, 'ListOfSDLCPhase'=>$c, 'TypeOfRequest'=>$d
        ]);
	}

	public function actionAssigned($id)
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
            $model = $this->findModel($id);

		if ($model->load(Yii::$app->request->post())) {
			$model->sdlc_phase= 'Code';


			if($model->save()){
				return $this->redirect(['view', 'id' => $model->task_id]);
			}

        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->task_id]);
        }
		$a= $model->getListAssignedTo();
		$b= $model->getAssigned();
		$c= $model->getSDLCPhase();
		$d= $model->getTypeOfRequest();
        return $this->render('assigned', [
            'model' => $model,'ListAssignedTo'=>$a, 'Assigned'=>$b, 'ListOfSDLCPhase'=>$c, 'TypeOfRequest'=>$d
        ]);
	}

		 public function actionCloseTask($id)
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
                     $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
			$model->sdlc_phase= 'Resolved';
			$model->close='yes';


			if($model->save()){
				return $this->redirect(['view', 'id' => $model->task_id]);
			}
		}

		//\Yii::$app->response->format = \yii\web\Response::FORMAT_HTML;
		$d= $model->getTypeOfRequest();
		/*return [
                    'title' => "Create New Observation Category",
                    'content' =>$this->renderAjax('close-task', [
                        'model' => $model,'TypeOfRequest'=>$d
                    ]),
                    'footer' => Html::button('Close', ['class' => 'btn btn-default pull-right', 'data-dismiss' => "modal"]) .
                    Html::button('Save', ['class' => 'btn btn-primary pull-left', 'type' => "submit"])
        ];*/
        return $this->render('close-task', [
            'model' => $model,'TypeOfRequest'=>$d
        ]);
    }

		 public function actionResolved($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->task_id]);
        }

        return $this->render('resolved', [
            'model' => $model,
        ]);
    }

    /**
     * Finds the Task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Task the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Task::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

	public function actionGraph1()
    {
        $model = new Task();


		$d= $model->getDataGraph1();

        return $this->render('data-graph1', [
             'data'=>$d,
        ]);


    }
}

frontend/views/task/_form.php
<?php

use yii\helpers\Html;
//use yii\widgets\ActiveForm;
use yii\bootstrap\ActiveForm;
/* @var $this yii\web\View */
/* @var $model frontend\models\Task */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="task-form">

    <?php $form =yii\bootstrap\ActiveForm::begin([
    'layout' => 'horizontal',
    'class' => 'form-horizontal',
    'fieldConfig' => [
    //'template' => "{input}{error}{label}",
    'horizontalCssClasses' => [
        'label' => 'col-sm-4',
        'offset' => 'col-sm-offset-4',
        'wrapper' => 'col-sm-7',
        'error' => '',
        'hint' => '',
    ],
]]
  ); ?>

    <div class="panel panel-default">
	<div class="panel-heading">Panel Heading</div>
	<div class="panel-body">
		<div class="col-md-6">
		
		<?= $form->field($model, 'case_id')->textInput() ?>

    <?= $form->field($model, 'practice_id')->textInput() ?>

    <?= $form->field($model, 'case_manager')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'request_received_on')->textInput() ?>

    <?= $form->field($model, 'no_of_pages')->textInput() ?>

    <?= $form->field($model, 'revised_pages')->textInput() ?>

	<?= $form->field($model, 'assigned_to')->dropdownList($ListAssignedTo,['prompt'=>'Select Assigned To']);?>

		</div>
		<div class="col-md-6">
		<?= $form->field($model, 'note')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'assigned_on')->dropDownList(['test'=>'test'],['prompt'=>'Select category']) ?>

	<?= $form->field($model, 'unplanned')->textInput(['maxlength' => true]) ?>
	
	<?= $form->field($model, 'sdlc_phase')->dropDownList($ListOfSDLCPhase,['prompt'=>'Select SDLC Phase']); ?>
	
	<?= $form->field($model, 'type_of_request')->dropDownList($TypeOfRequest,['prompt'=>'Select Type Of Request']);?>
	
	<?= $form->field($model, 'file_type')->textInput(['maxlength' => true]) ?>
	
	<?= $form->field($model, 'estimated_time')->textInput(['maxlength' => true]) ?>
	</div>

		</div>
	</div>
	
   <!-- <?= $form->field($model, 'reviewer')->dropDownList($Reviewer,['prompt'=>'Select Reviewer']) ?>

    <?= $form->field($model, 'review_assigned_on')->textInput() ?>

    <?= $form->field($model, 'review_done')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'review_done_on')->textInput() ?>

    <?= $form->field($model, 'send_for_review')->textInput(['maxlength' => true]) ?>

    
<hr class="mb-4"/>

    <div class="panel panel-default">
	<div class="panel-heading">Panel Heading</div>
	<div class="panel-body">
		<div class="col-md-6">
		<?= $form->field($model, 'recode_sent_to')->textInput(['maxlength' => true]) ?>
		 <?= $form->field($model, 'recode_sent_on')->textInput() ?>

    <?= $form->field($model, 'send_for_recode')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'close')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'closed_date')->textInput()?>

    
		</div>
		<div class="col-md-6">
		  

    

    

    

    <?= $form->field($model, 'development_time')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'review_time')->textInput(['maxlength' => true]) ?>
		</div>
	</div>
	</div>
   <hr class="mb-4"/>//-->

  

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/task/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\TaskSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="task-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'task_id') ?>

    <?= $form->field($model, 'case_id') ?>

    <?= $form->field($model, 'practice_id') ?>

    <?= $form->field($model, 'case_manager') ?>

    <?= $form->field($model, 'request_received_on') ?>

    <?php // echo $form->field($model, 'no_of_pages') ?>

    <?php // echo $form->field($model, 'revised_pages') ?>

    <?php // echo $form->field($model, 'assigned_to') ?>

    <?php // echo $form->field($model, 'note') ?>

    <?php // echo $form->field($model, 'assigned_on') ?>

    <?php // echo $form->field($model, 'reviewer') ?>

    <?php // echo $form->field($model, 'review_assigned_on') ?>

    <?php // echo $form->field($model, 'review_done') ?>

    <?php // echo $form->field($model, 'review_done_on') ?>

    <?php // echo $form->field($model, 'send_for_review') ?>

    <?php // echo $form->field($model, 'recode_sent_to') ?>

    <?php // echo $form->field($model, 'recode_sent_on') ?>

    <?php // echo $form->field($model, 'send_for_recode') ?>

    <?php // echo $form->field($model, 'close') ?>

    <?php // echo $form->field($model, 'closed_date') ?>

    <?php // echo $form->field($model, 'unplanned') ?>

    <?php // echo $form->field($model, 'sdlc_phase') ?>

    <?php // echo $form->field($model, 'type_of_request') ?>

    <?php // echo $form->field($model, 'file_type') ?>

    <?php // echo $form->field($model, 'estimated_time') ?>

    <?php // echo $form->field($model, 'development_time') ?>

    <?php // echo $form->field($model, 'review_time') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/task/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use frontend\models\Roles;
//use kartik\grid\GridView;
//use kartik\export\ExportMenu;
/* @var $this yii\web\View */
/* @var $searchModel frontend\models\TaskSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Tasks';
//$this->params['breadcrumbs'][] = $this->title;
?>
<?php 

if (Yii::$app->user->identity->role=='admin' ) { 
 $menuitems[]=['label' => 'Reports', 'url' => ['/report']];
}            
?>
<style>
.row{
  border: 1px dash red;
}
</style>
<div class="task-index">


 
  </div>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
  <div class="row">
   <div class="col-md-6"><span class="col-md-6 h1"><?= Html::encode($this->title) ?></span></div>
   <div class="col-md-6 text-right"><p>
     <?php
     if(Roles::hasAdmin())
     {
       echo Html::a('Create Task', ['create'], ['class' => 'btn btn-success']);
     } ?>
   </p></div>
 </div>
 
 <?php 
  

  $gridColumns = [
        //['class' => 'yii\grid\SerialColumn'],
        'case_id',
        'request_received_on',
        'no_of_pages',
        'closed_date',
        'type_of_request',
        //['class' => 'yii\grid\ActionColumn'],
        // 'practice_id',
        'case_manager',
        //'revised_pages',
        //'assigned_to',
        //'note',
        //'assigned_on',
        //'reviewer',
        //'review_assigned_on',
        //'review_done',
        //'review_done_on',
        //'send_for_review',
        //'recode_sent_to',
        //'recode_sent_on',
        //'send_for_recode',
        //'close',
        //'closed_date',
        //'unplanned',
        //'sdlc_phase',
        //'type_of_request',
        //'file_type',
        //'estimated_time',
        //'development_time',
        //'review_time',
        //'role',
        //['class' => 'yii\grid\ActionColumn'],
  ];

  // Renders a export dropdown menu
  /*echo ExportMenu::widget([
      'dataProvider' => $dataProvider,
      'columns' => $gridColumns,
  ]);
*/
  ?>




 <?= GridView::widget([
  'dataProvider' => $dataProvider,
  'filterModel' => $searchModel,
  'columns' => [
    ['class' => 'yii\grid\SerialColumn'],

    [
     'attribute'=>'task_id',
     'format' => 'raw',
     'value'=>function ($data) {
      return Html::a($data->task_id,['task/view','id'=>$data->task_id]);
    },
    ],
  'case_id',
          // 'practice_id',
          // 'case_manager',
  'request_received_on',
  'no_of_pages',
        //'revised_pages',
  'assigned_to',
            //'note',
  'assigned_on',
  'reviewer',
            //'review_assigned_on',
            //'review_done',
            //'review_done_on',
            //'send_for_review',
            //'recode_sent_to',
            //'recode_sent_on',
            //'send_for_recode',
            //'close',
            //'closed_date',
            //'unplanned',
  'sdlc_phase',
            //'type_of_request',
            //'file_type',
            //'estimated_time',
            //'development_time',
            //'review_time',
             //'role',
            //['class' => 'yii\grid\ActionColumn'],

      [
          'class' => 'yii\grid\ActionColumn',
          'header' => 'Actions',
          'headerOptions' => ['style' => 'color:#337ab7'],
          'template' => '{view}{update}{delete}',
          'buttons' => [
            
            'view' => function ($url, $model) 
            {
              return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, 
              [
                  'title' => Yii::t('app', 'lead-view'),
              ]);
            },  
            'update' => function ($url, $model) 
            {
              if(Roles::hasAdmin()) 
              {
              return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, 
              [
              'title' => Yii::t('app', 'lead-update'),
              ]);
              }
            },  

            'delete' => function ($url, $model) {
              if(Roles::hasAdmin()) 
              { 

              return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url,

              [
              'title' => Yii::t('app', 'lead-delete'),
              'data' => [
              'confirm' => 'Are you sure you want to delete this item?',
              'method' => 'post',
              ],
              ]);
            }}, 
          ]
      ]
    ]
  ]);?>