frontend/models/Report.php
<?php
namespace frontend\models;
use yii\db\Query;
use Yii;

class Report extends \yii\db\ActiveRecord {
    public static function tableName(){
        return 'task';
    }
	
    public function getDataGraph1($start_date, $end_date){
        $query= new Query();
        $query->SELECT(['type_of_request',"count(task_id) as cases_closed","sum(no_of_pages) as pages_closed"])
                    ->from('task')
                    ->where("close='yes'");
                    if(!empty($start_date)){
                        
                        $query->andWhere(['>=','request_received_on',date('Y-m-d',strtotime($start_date) )]);
                    }
                    if(!empty($end_date)){
                        $query->andWhere(['<=','request_received_on',date('Y-m-d',strtotime($end_date) )]);
                    }
                    $query->groupby('type_of_request');
                    $data = $query->all();
        return $data;
    }
        
    public function getDataGraph2($start_date, $end_date){
        $query= new Query();
        $query->SELECT(['type_of_request',"count(task_id) as cases_closed","sum(no_of_pages) as pages_closed"])
                    ->from('task')
                    ->where("close='yes'");
                    if(!empty($start_date)){
                        
                        $query->andWhere(['>=','request_received_on',date('Y-m-d',strtotime($start_date) )]);
                    }
                    if(!empty($end_date)){
                        $query->andWhere(['<=','request_received_on',date('Y-m-d',strtotime($end_date) )]);
                    }
                    $query->groupby('type_of_request');
                    $data=$query->all();
        return $data;
    }
    
    public function getDataGraph3($start_date, $end_date){
        $query= new Query();
        $query->SELECT(["sum(case when unplanned='yes' then 1 else 0 end) as unplanned",
                                "sum(case when unplanned!='yes' or unplanned is null then 1 else 0 end) as planned",
                                "sum(no_of_pages) as pages_closed",
                                "WEEK(request_received_on) as week",
                                "request_received_on - INTERVAL WEEKDAY(request_received_on) Day as mondaythisweek",
                                'request_received_on'])
                    ->from('task')
                    ->where("close='yes'");
                    if(!empty($start_date)){
                        
                        $query->andWhere(['>=','request_received_on',date('Y-m-d',strtotime($start_date) )]);
                    }
                    if(!empty($end_date)){
                        $query->andWhere(['<=','request_received_on',date('Y-m-d',strtotime($end_date) )]);
                    }
                    $query->groupby("WEEK(request_received_on)");
                    $data=$query->all();
        return $data;
    }
    
    public function getDataGraph4(){
        $query= new Query();
        $data= $query->SELECT(["sum(case when unplanned='yes' then 1 else 0 end) as unplanned","sum(case when unplanned!='yes' or unplanned is null then 1 else 0 end) as planned","sum(no_of_pages) as pages_closed",'type_of_request'])
                    ->from('task')
                    ->where("close='yes'")
                    ->groupby('type_of_request')
                    ->all();
        return $data;
    }
    
    public function getDataGraph5(){
        $query= new Query();
        $data= $query->SELECT(["sum(case when unplanned='yes' then 1 else 0 end) as unplanned","sum(case when unplanned!='yes' or unplanned is null then 1 else 0 end) as planned","sum(no_of_pages) as pages_closed",'type_of_request'])
                    ->from('task')
                    ->where("close='yes'")
                    ->groupby('type_of_request')
                    ->all();
        return $data;
    }
        
    public function getDataGraph6($start_date, $end_date){
        $query= new Query();
        $data= $query->SELECT(["sum(case when no_of_pages <= 10 then 1 else 0 end) as small_task","sum(case when no_of_pages >= 10 and no_of_pages <=25 then 1 else 0 end) as medium_task", "sum(case when no_of_pages >= 25 then 1 else 0 end) as large_task"])
                    ->from('task');
                    if(!empty($start_date)){
                        
                        $query->Where(['>=','request_received_on',date('Y-m-d',strtotime($start_date) )]);
                    }
                    if(!empty($end_date)){
                        $query->andWhere(['<=','request_received_on',date('Y-m-d',strtotime($end_date) )]);
                    }
                     $data=$query->all();
        return $data;
    }
    
    public function getDataGraph7(){
        $query= new Query();
        $data= $query->SELECT(["sum(case when unplanned='yes' then 1 else 0 end) as unplanned","sum(case when unplanned!='yes' or unplanned is null then 1 else 0 end) as planned","sum(no_of_pages) as pages_closed",'type_of_request'])
                    ->from('task')
                    ->where("close='yes'")
                    ->groupby('type_of_request')
                    ->all();
        return $data;
    }
    
    public function getDataGraph8(){
        $query= new Query();
        $data= $query->SELECT(["sum(case when unplanned='yes' then 1 else 0 end) as unplanned","sum(case when unplanned!='yes' or unplanned is null then 1 else 0 end) as planned","sum(no_of_pages) as pages_closed",'type_of_request'])
                    ->from('task')
                    ->where("close='yes'")
                    ->groupby('type_of_request')
                    ->all();
        return $data;
    }
    
    public function getDataGraph9(){
        $query= new Query();
        $data= $query->SELECT(["sum(case when unplanned='yes' then 1 else 0 end) as unplanned","sum(case when unplanned!='yes' or unplanned is null then 1 else 0 end) as planned","sum(no_of_pages) as pages_closed",'type_of_request'])
                    ->from('task')
                    ->where("close='yes'")
                    ->groupby('type_of_request')
                    ->all();
        return $data;
    }
    
    public function getDataGraph10(){
        $query= new Query();
        $data= $query->SELECT(["sum(case when unplanned='yes' then 1 else 0 end) as unplanned","sum(case when unplanned!='yes' or unplanned is null then 1 else 0 end) as planned","sum(no_of_pages) as pages_closed",'type_of_request'])
                    ->from('task')
                    ->where("close='yes'")
                    ->groupby('type_of_request')
                    ->all();
        return $data;
    }
    
    public function getDataGraph11(){
        $query= new Query();
        $data= $query->SELECT(["sum(case when unplanned='yes' then 1 else 0 end) as unplanned","sum(case when unplanned!='yes' or unplanned is null then 1 else 0 end) as planned","sum(no_of_pages) as pages_closed",'type_of_request'])
                    ->from('task')
                    ->where("close='yes'")
                    ->groupby('type_of_request')
                    ->all();
        return $data;
    }
					
    public function rules(){
        return [
            [['case_id'], 'required'],
			 [['case_id'], 'unique'],
            [['case_id', 'practice_id', 'no_of_pages', 'revised_pages'], 'integer'],
            [['request_received_on', 'assigned_on', 'review_assigned_on', 'review_done_on', 'recode_sent_on', 'closed_date'], 'safe'],
            [['estimated_time', 'development_time', 'review_time'], 'number'],
            [['case_manager', 'assigned_to', 'note', 'reviewer', 'send_for_review', 'recode_sent_to'], 'string', 'max' => 50],
            [['review_done', 'send_for_recode', 'close', 'unplanned', 'sdlc_phase', 'file_type'], 'string', 'max' => 10],
            [['type_of_request'], 'string', 'max' => 25],
        ];
    }

    public function attributeLabels(){
        return [
            'task_id' => 'Task ID',
            'case_id' => 'Case ID',
            'practice_id' => 'Practice ID',
            'case_manager' => 'Case Manager',
            'request_received_on' => 'Request Received On',
            'no_of_pages' => 'No Of Pages',
            'revised_pages' => 'Revised Pages',
            'assigned_to' => 'Assigned To',
            'note' => 'Note',
            'assigned_on' => 'Assigned On',
            'reviewer' => 'Reviewer',
            'review_assigned_on' => 'Review Assigned On',
            'review_done' => 'Review Done',
            'review_done_on' => 'Review Done On',
            'send_for_review' => 'Send For Review',
            'recode_sent_to' => 'Recode Sent To',
            'recode_sent_on' => 'Recode Sent On',
            'send_for_recode' => 'Send For Recode',
            'close' => 'Close',
            'closed_date' => 'Closed Date',
            'unplanned' => 'Unplanned',
            'sdlc_phase' => 'Sdlc Phase',
            'type_of_request' => 'Type Of Request',
            'file_type' => 'File Type',
            'estimated_time' => 'Estimated Time',
            'development_time' => 'Development Time',
            'review_time' => 'Review Time',
        ];
    }
}

frontend/controllers/ReportController.php
<?php
namespace frontend\controllers;
use Yii;
use frontend\models\Report;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\web\Request;

class ReportController extends Controller {
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex() {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        return $this->render('index', []);
    }

    public function actionGraph1() {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new Report();
        $request = new Request();
        $start_date=$request->post('start_date', '');
        $end_date=$request->post('end_date', '');
        $d = $model->getDataGraph1($start_date, $end_date);
        return $this->render('data-graph1', ['data' => $d, 'start_date'=>$start_date,'end_date'=>$end_date]);
    }
    
    public function actionGraph2() {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new Report();
        $request = new Request();
        $start_date=$request->post('start_date', '');
        $end_date=$request->post('end_date', '');
        $d = $model->getDataGraph2($start_date, $end_date);
        return $this->render('data-graph2', ['data' => $d,'start_date'=>$start_date,'end_date'=>$end_date]);
    }

    public function actionGraph3() {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new Report();
        $request = new Request();
        $start_date=$request->post('start_date', '');
        $end_date=$request->post('end_date', '');
        $d = $model->getDataGraph3($start_date, $end_date);
        return $this->render('data-graph3', ['data' => $d,'start_date'=>$start_date,'end_date'=>$end_date]);
    }
    
    public function actionGraph4() {
        $model = new Report();
        $d = $model->getDataGraph4();
        return $this->render('data-graph4', ['data' => $d,]);
    }
    
    public function actionGraph5() {
        $model = new Report();
        $d = $model->getDataGraph5();
        return $this->render('data-graph5', ['data' => $d,]);
    }
    
    public function actionGraph6() {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new Report();
        $request = new Request();
        $start_date=$request->post('start_date', '');
        $end_date=$request->post('end_date', '');
        $d = $model->getDataGraph6($start_date, $end_date);
        return $this->render('data-graph6', ['data' => $d,'start_date'=>$start_date,'end_date'=>$end_date]);
    }
    
    public function actionGraph7() {
        $model = new Report();
        $d = $model->getDataGraph7();
        return $this->render('data-graph7', ['data' => $d,]);
    }

    public function actionGraph8() {
        $model = new Report();
        $d = $model->getDataGraph8();
        return $this->render('data-graph8', ['data' => $d,]);
    }
    
    public function actionGraph9() {
        $model = new Report();
        $d = $model->getDataGraph9();
        return $this->render('data-graph9', ['data' => $d,]);
    }
    
    public function actionGraph10() {
        $model = new Report();
        $d = $model->getDataGraph10();
        return $this->render('data-graph10', ['data' => $d,]);
    }
    
    public function actionGraph11() {
        $model = new Report();
        $d = $model->getDataGraph11();
        return $this->render('data-graph11', ['data' => $d,]);
    }
}

frontend/views/report/data-graph1.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use miloschuman\highcharts\Highcharts;
?>

<script src="https://code.highcharts.com/highcharts-3d.js"></script>

<?php
    $data_cases_closed = [];
    foreach ($data as $key => $row) {
        $data_cases_closed[] = [$row['type_of_request'], (int) $row['cases_closed']];
    }
    $data_pages_closed = [];
    foreach ($data as $key => $row) {
        $data_pages_closed[] = [$row['type_of_request'], (int) $row['pages_closed']];
    }
?>

<div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title">BSDT: Cases v/s Pages Closed</h3></div>
    <div class="panel-body">
        <?= $this->render('form', ['action'=>['report/graph1'], 'start_date'=>$start_date, 'end_date'=>$end_date])?>
        <div id="container2" class="col-md-6 panel panel-default pull-left"></div>
        <div id="container1" class="col-md-6 panel panel-default pull-right"></div>
        <table class='table table-striped table-bordered'>
            <tr>
                <th>Cases v/s Pages closed</th>
                <?php
                    foreach ($data as $key => $row) {
                        echo"<th width=16%>";
                        echo $row['type_of_request'];
                        echo"</th>";
                    }
                ?>
                <th width=18%> Total </th>
            </tr>
            <tr>
                <th>Cases closed</th>
                <?php
                    $total = 0;
                    foreach ($data as $key => $row) {
                        echo"<td width=16%>";
                        echo $row['cases_closed'];
                        echo"</td>";
                        $total = $row['cases_closed'] + $total;
                    }
                ?>
                <td width=18%> 
                    <?= $total ?>
                </td>
            </tr>
            <tr>
                <th>Pages closed</th>
                <?php
                    $total1 = 0;
                    foreach ($data as $key => $row) {
                        echo"<td width=16%>" . $row['pages_closed'] . "</td>";
                        $total1 = $row['pages_closed'] + $total1;
                    }
                ?>
                <td width=18%>
                    <?= $total1 ?>
                </td>
            </tr>
        </table>	

      
    </div>
</div>

<script>
    Highcharts.chart('container2', {
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie',
            options3d: {
                enabled: true,
                alpha: 45,
                beta: 0
            }
        },
         credits: {
              enabled: false
        },
        title: {
            text: 'Cases Closed'
        },
        credits: {
            enabled: false
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                depth: 35,
                dataLabels: {
                    enabled: true,
                    format: ' {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    },
                },
                showInLegend: true
            }
        },
        series: [{
            name: 'Cases Closed',
            colorByPoint: true,
            data: <?php echo json_encode($data_cases_closed) ?>
        }]
    });

    Highcharts.chart('container1', {
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie',
            options3d: {
                enabled: true,
                alpha: 45,
                beta: 0
            }
        },
         credits: {
              enabled: false
        },
        title: {
            text: 'Pages Closed'
        },
        credits: {
            enabled: false
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                depth: 35,
                dataLabels: {
                    enabled: true,
                    format: '{point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    },
                },
                showInLegend: true
            }
        },
        series: [{
                name: 'Pages Closed',
                colorByPoint: true,
                data: <?php echo json_encode($data_pages_closed) ?>
        }]
    });
</script>
        	

frontend/views/report/data-graph10.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

frontend/views/report/data-graph11.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

frontend/views/report/data-graph2.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use miloschuman\highcharts\Highcharts;
?>

<?php
    $categories= [];
    foreach ($data as $key => $row) {
        $categories[] = $row['type_of_request'];
    }
    $data_cases_closed = [];
    foreach ($data as $key => $row) {
        $data_cases_closed[] = [$row['type_of_request'], (int) $row['cases_closed']];
    }
    $data_pages_closed = [];
    foreach ($data as $key => $row) {
        $data_pages_closed[] = [$row['type_of_request'], (int) $row['pages_closed']];
    }
?>

<div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title"> BSDT: Trend – Closed Cases v/s Closed Pages</h3></div>
    <div class="panel-body">
        <?= $this->render('form', ['action'=>['report/graph2'], 'start_date'=>$start_date, 'end_date'=>$end_date])?>
        <div id="container1" class="col-md-12 panel panel-default "></div>
        <table class='table table-striped table-bordered'>
            <tr>
                <th></th>
                <?php
                    foreach ($data as $key => $row) {
                        echo"<tH width=20%>";
                        echo $row['type_of_request'];
                        echo"</th>";
                    }
                ?>
            </tr>
            <tr>
                <th>Cases closed</th>
                <?php
                    $total = 0;
                    foreach ($data as $key => $row) {
                        echo"<td width=20%>";
                        echo $row['cases_closed'];
                        echo"</td>";
                    }
                ?>
            </tr>
            <tr>
                <th>Pages closed</th>
                <?php
                    $total1 = 0;
                    foreach ($data as $key => $row) {
                        echo"<td width=20%>" . $row['pages_closed'] . "</td>";
                    }
                ?>
            </tr>
        </table>

      
    </div>
</div>

<script>
    Highcharts.chart('container1', {
        chart: {
            type: 'spline'
        },
        title: {
            text: 'Closed Cases v/s Closed Pages'
        },
        credits: {
              enabled: false
        },
        xAxis: {
            categories:<?php echo json_encode($categories) ?>
        },
        yAxis: {
            title: {
                text: 'Count'
            },
            labels: {
                formatter: function () {
                    return this.value + '';
                }
            }
        },
        tooltip: {
            crosshairs: true,
            shared: true
        },
        credits: {
            enabled: false
        },
        plotOptions: {
            spline: {
                marker: {
                    radius: 0,
                    lineColor: '#000',
                    lineWidth: 0
                }
            }
        },
        series: [{
            name: 'Cases Closed',
            color: "blue",
            data: <?php echo json_encode($data_cases_closed) ?>
            },
            {
                name: 'Pages Closed',
                color: "red",
                data: <?php echo json_encode($data_pages_closed) ?>
        }]
    });
</script>

frontend/views/report/data-graph3.php
<?php
    use yii\helpers\Html;
    use yii\grid\GridView;
    use miloschuman\highcharts\Highcharts;
?>

<?php
    $unplanned = [];
    foreach ($data as $key => $row) {
        $unplanned[] = [$row['mondaythisweek'], (int) $row['unplanned']];
    }
    $planned = [];
    foreach ($data as $key => $row) {
        $planned[] = [$row['mondaythisweek'], (int) $row['planned']];
    }
    $data_pages_closed = [];
    foreach ($data as $key => $row) {
        $data_pages_closed[] = [$row['mondaythisweek'], (int) $row['pages_closed']];
    }
?>

<div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title">BSDT: Trend of Tasks Planned (Salesforce) vs Unplanned (via Email)</h3></div>
    <div class="panel-body">
        <?= $this->render('form', ['action'=>['report/graph3'], 'start_date'=>$start_date, 'end_date'=>$end_date])?>
        <div id="container1" class="col-md-12 panel panel-default "></div>
        <table class='table table-striped table-bordered'>
            <tr>
                <th></th>
                <?php
                    foreach ($data as $key => $row) {
                        echo"<th width=10%>";
                        echo $row['mondaythisweek'];
                        echo"</th>";
                }
                ?>
            </tr>
            <tr>
                <th width=10%>via SF</th>
                <?php
                    foreach ($data as $key => $row) {
                        echo"<td width=10%>";
                        echo $row['planned'];
                        echo"</td>";
                    }
                ?>
            </tr>
            <tr>
                <th>via Email</th>
                <?php
                    foreach ($data as $key => $row) {
                        echo"<td width=10%>" . $row['unplanned'] . "</td>";
                    }
                ?>
            </tr>
        </table>

    
    </div>
</div> 

<script>
    Highcharts.chart('container1', {
        chart: {
            type: 'spline'
        },
        title: {
            text: 'Trend of Tasks (Planned (Salesforce) vs Unplanned (via Email)'
        },
        credits: {
              enabled: false
        },
        xAxis: {
            categories:<?php echo json_encode(  $data_pages_closed) ?>
        },
        yAxis: {
            title: {
                text: 'No of pages coded'
            },
            labels: {
                formatter: function () {
                    return this.value + '';
                }
            }
        },
        tooltip: {
            crosshairs: true,
            shared: true
        },
        credits: {
            enabled: false
        },
        plotOptions: {
            spline: {
                marker: {
                    radius:0,
                    lineColor: '#000',
                    lineWidth: 0
                }
            }
        },
        series: [{
                name: 'Unplanned',
                color:"red",
                data: <?php echo json_encode( $unplanned) ?>
            }, 
            {
                name: 'Planned',
                color:"blue",
                data: <?php echo json_encode( $planned) ?>
        }]
    });
</script>

frontend/views/report/data-graph4.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

frontend/views/report/data-graph5.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

frontend/views/report/data-graph6.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use miloschuman\highcharts\Highcharts;
?>

<script src="https://code.highcharts.com/highcharts-3d.js"></script>

<?php
    foreach ($data as $key => $row) {
        $small= $row['small_task'];
        $medium= $row['medium_task'];
        $large= $row['large_task'];
    }
?>

<div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title"> Task Size</h3></div>
    <div class="panel-body">
        <?= $this->render('form', ['action'=>['report/graph6'], 'start_date'=>$start_date, 'end_date'=>$end_date])?>
        <div id="container1" class="col-md-12 panel panel-default "></div>
        <table class='table table-striped table-bordered'>
            <tr>
                <th>&nbsp;</th>
                <th>Small</th>
                <th>Medium</th>
                <th>Large</th>
            </tr>
            <tr>
                <th>Task Size</th>
                <?php
                    foreach ($data as $key => $row) {
                        echo"<td width=25%>";
                        echo $row['small_task'];
                        echo"</td>";
                    }
                ?>

                <?php
                    $total = 0;
                    foreach ($data as $key => $row) {
                        echo"<td width=25%>";
                        echo $row['medium_task'];
                        echo"</td>";
                    }
                ?>

                <?php
                    foreach ($data as $key => $row) {
                        echo"<td width=25%>";
                        echo $row['large_task'];
                        echo"</td>";
                    }
                ?>
            </tr>
        </table>

        
    </div>
</div>

<script>
    Highcharts.chart('container1', {
        chart: {
            type: 'column',
            options3d: {
                enabled: true,
                alpha: 0,
                beta: 0,
                depth: 20,
                viewDistance: 25
            }
        },
         credits: {
              enabled: false
        },
        title: {
            text: 'Task Size'
        },
        xAxis: {
            type: 'category'
        },
        yAxis: {
            title: {
                text: 'Total Pages'
            }
        },
        legend: {
            enabled: false
        },
        plotOptions: {
            column: {
                depth: 15
            },
            series: {
                borderWidth: 0,
                dataLabels: {
                    enabled: true,
                    format: '{point.y:.1f}%'
                }
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
            pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
        },
        credits: {
            enabled: false
        },
        "series": [
            {
                "name": "Task Size",
                "data": [
                    {
                        "name": "Small",
                        "y": <?php echo $small ?>,
                    },
                    {
                        "name": "Medium", 
                        "y": <?php echo $medium ?>,
                    },
                    {
                        "name": "Large",
                        "y": <?php echo $large ?>,
                    }
                ]
            }
        ]
    });
</script>

frontend/views/report/data-graph7.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

frontend/views/report/data-graph8.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

frontend/views/report/data-graph9.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

frontend/views/report/form.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
?>
<style>
    .ml-10{
        margin-left:10px;
    }
</style>

<div class="row">
    <?= Html::beginForm($action, 'POST');?>
    <div class="form-group field-task-practice_id col-md-12">
        <label class="control-label pull-left" >Start Date</label>
        <div class="col-md-2 pull-left ml-10">
            <input type="date" class="form-control " name="start_date" value="<?= $start_date?>">
        </div>
        <label class="control-label pull-left ml-10" >End Date</label>
        <div class="col-md-2 pull-left ml-10">
            <input type="date"  class="form-control" name="end_date" value="<?= $end_date?>">
        </div>
        <div class="form-group col-sm-2">
        <?= Html::submitButton('Submit', ['class' => 'btn btn-success']) ?>
    </div>
    </div>
<?= Html::endForm();?>
</div>