backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout="dashboardLayout";
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/controllers/TaskController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Task;
use frontend\models\TaskSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
//use yii\filters\AccessControl;
use yii\helpers\Html;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [

		   'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Task models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model= new Task();
		$searchModel = new TaskSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		$a= $model->getRole();
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider, 'role'=>$a
        ]);
    }

    /**
     * Displays a single Task model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new Task();
		$a= $model->getListAssignedTo();
		$b= $model->getReviewer();
		$c= $model->getSDLCPhase();
		$d= $model->getTypeOfRequest();
		$e= $model->getAssigned();
		return $this->render('view', [
            'model' => $this->findModel($id),'ListAssignedTo'=>$a,'Reviewer'=>$b , 'ListOfSDLCPhase'=>$c, 'TypeOfRequest'=>$d, 'Assigned'=>$e
        ]);
    }

    /**
     * Creates a new Task model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new Task();

        if ($model->load(Yii::$app->request->post())) {
			$model->sdlc_phase= '';



			if($model->save()){
				return $this->redirect(['view', 'id' => $model->task_id]);
			}

        }
		$a= $model->getFileType();
		$b= $model->getReviewer();
		$c= $model->getSDLCPhase();
		$d= $model->getTypeOfRequest();
        return $this->render('create', [
            'model' => $model,   'Reviewer'=>$b, 'ListOfSDLCPhase'=>$c, 'TypeOfRequest'=>$d, 'FileType'=>$a
        ]
		);
    }

    /**
     * Updates an existing Task model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->task_id]);
        }
		$a= $model->getListAssignedTo();
		$b= $model->getReviewer();
		$c= $model->getSDLCPhase();
		$d= $model->getTypeOfRequest();
		$e= $model->getAssigned();
		$f= $model->getFileType();
        return $this->render('update', [
            'model' => $model, 'ListAssignedTo'=>$a,'Reviewer'=>$b , 'ListOfSDLCPhase'=>$c, 'TypeOfRequest'=>$d, 'Assigned'=>$e, 'FileType'=>$f
        ]);
    }

    /**
     * Deletes an existing Task model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

	 public function actionSendForReview($id)
    {
             if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
             $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
			       $model->sdlc_phase= 'Review';



			if($model->save()){
				return $this->redirect(['view', 'id' => $model->task_id]);
			}

        }
		$a= $model->getListAssignedTo();
		$c= $model->getSDLCPhase();
		$d= $model->getTypeOfRequest();
        return $this->render('send-for-review', [
            'model' => $model,'ListAssignedTo'=>$a, 'ListOfSDLCPhase'=>$c, 'TypeOfRequest'=>$d
        ]);
    }

	public function actionSendForRecode($id)
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
            $model = $this->findModel($id);


        if ($model->load(Yii::$app->request->post())) {
			$model->sdlc_phase= 'Recode';
			$model->review_done='yes';

			if($model->save()){
				return $this->redirect(['view', 'id' => $model->task_id]);
			}

        }
		$a= $model->getListAssignedTo();
		$c= $model->getSDLCPhase();
		$d= $model->getTypeOfRequest();
        return $this->render('send-for-recode', [
            'model' => $model,'ListAssignedTo'=>$a, 'ListOfSDLCPhase'=>$c, 'TypeOfRequest'=>$d
        ]);
	}

	public function actionAssigned($id)
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
            $model = $this->findModel($id);

		if ($model->load(Yii::$app->request->post())) {
			$model->sdlc_phase= 'Code';


			if($model->save()){
				return $this->redirect(['view', 'id' => $model->task_id]);
			}

        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->task_id]);
        }
		$a= $model->getListAssignedTo();
		$b= $model->getAssigned();
		$c= $model->getSDLCPhase();
		$d= $model->getTypeOfRequest();
        return $this->render('assigned', [
            'model' => $model,'ListAssignedTo'=>$a, 'Assigned'=>$b, 'ListOfSDLCPhase'=>$c, 'TypeOfRequest'=>$d
        ]);
	}

		 public function actionCloseTask($id)
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
                     $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
			$model->sdlc_phase= 'Resolved';
			$model->close='yes';


			if($model->save()){
				return $this->redirect(['view', 'id' => $model->task_id]);
			}
		}

		//\Yii::$app->response->format = \yii\web\Response::FORMAT_HTML;
		$d= $model->getTypeOfRequest();
		/*return [
                    'title' => "Create New Observation Category",
                    'content' =>$this->renderAjax('close-task', [
                        'model' => $model,'TypeOfRequest'=>$d
                    ]),
                    'footer' => Html::button('Close', ['class' => 'btn btn-default pull-right', 'data-dismiss' => "modal"]) .
                    Html::button('Save', ['class' => 'btn btn-primary pull-left', 'type' => "submit"])
        ];*/
        return $this->render('close-task', [
            'model' => $model,'TypeOfRequest'=>$d
        ]);
    }

		 public function actionResolved($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->task_id]);
        }

        return $this->render('resolved', [
            'model' => $model,
        ]);
    }

    /**
     * Finds the Task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Task the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Task::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

	public function actionGraph1()
    {
        $model = new Task();


		$d= $model->getDataGraph1();

        return $this->render('data-graph1', [
             'data'=>$d,
        ]);


    }
}

frontend/views/site/Dashboard.php
<?php
use frontend\models\Task;

    $model_Task=new Task();
    
    $TotalCountTask = $model_Task->getCountTotalTask();
    $TotalCloseTask = $model_Task->getTotalCloseTask();
    $TotalOpenTask = $model_Task->getTotalOpenTask();
    $TotalPagesCoded = $model_Task->getTotalPagesCoded();
?>
<style>
    .glyphicon { top:10px;}
    .content {
        min-height: 130px;
    }
    .wrap {padding: 0 0 40px;}
</style>

<div class="wrap">

  <!-- Content Wrapper. Contains page content -->

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>Dashboard </h1>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row">
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-aqua">
            <div class="inner">
              <h3><?= $TotalCountTask ?></h3>
               <p>Total Task</p>
            </div>
            <div class="icon">
              <span class="glyphicon glyphicon glyphicon-file"></span>
            </div>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-green">
            <div class="inner">
              <h3><?= $TotalCloseTask ?></h3>
              <p>Close Task</p>
            </div>
            <div class="icon">
              <span class="glyphicon glyphicon glyphicon-file"></span>
            </div>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-yellow">
            <div class="inner">
              <h3><?= $TotalOpenTask ?></h3>
              <p>Open Task</p>
            </div>
            <div class="icon">
              <span class="glyphicon glyphicon glyphicon-file"></span>
            </div>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-red">
            <div class="inner">
              <h3><?= $TotalPagesCoded ?></h3>
              <p>Pages Coded</p>
            </div>
            <div class="icon">
              <span class="glyphicon glyphicon glyphicon-file"></span>
            </div>
          </div>
        </div>
        <!-- ./col -->
      </div>


    </section>

</div>

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use miloschuman\highcharts\Highcharts;
//use yii\captcha\Captcha;

//$this->title = 'Contact';
//$this->params['breadcrumbs'][] = $this->title;


?>
 <div class="body-content">
        <div class="row">
               <?=  
                     Highcharts::widget([
                       'options' => [
                          'chart'=>['type'=>'column'],

                          'title' => ['text' => 'Monthly Open Cases'],
                          'xAxis' => [
                             'categories' => ['Clinical Code', 'Clinical Tweak', 'Collector Code', 'Collector Tweak']
                          ],
                          'yAxis' => [
                             'title' => ['text' => 'Open Cases']
                          ],
                          'series' => [
                             ['name' => 'Jan', 'data' => [1, 0, 4, 5]],
                             ['name' => 'Feb', 'data' => [5, 7, 3, 14]],
                             ['name' => 'March', 'data' => [5, 7, 3, 30]],
                             ['name' => 'Apr', 'data' => [5, 7, 3, 6]]
                          ]
                       ]
                    ]);                       
                 ?> 
        </div>  
          <div class="row">
               <?=  
                     Highcharts::widget([
                       'options' => [
                          'chart'=>['type'=>'pie'],

                          'title' => ['text' => 'Monthly Open Cases'],
                           'series' => [
                                        ['type'=>'pie'],
                                        ['name'=>'open Cases'],
                                        ['data'=> [
                                                    ['Clinical Code',  45.0],
                                                    ['Clinical Tweak', 26.8],   
                                                    ['Collector Code', 8.5],
                                                    ['Collector Tweak',  6.2],
                                                  ]
                                        ]
                                    ]
                       ]
                    ]);                       
                 ?> 
        </div>  
           
</div>            

frontend/views/site/dashboardgraph1.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use miloschuman\highcharts\Highcharts;
use frontend\models\Report;
use frontend\models\Task;
?>

<script src="https://code.highcharts.com/highcharts-3d.js"></script>

<?php
        $model = new Report();
        $start_date='';
        $end_date='';
        $data = $model->getDataGraph1($start_date, $end_date);
        
    $data_cases_closed = [];
    foreach ($data as $key => $row) {
        $data_cases_closed[] = [$row['type_of_request'], (int) $row['cases_closed']];
    }
    $data_pages_closed = [];
    foreach ($data as $key => $row) {
        $data_pages_closed[] = [$row['type_of_request'], (int) $row['pages_closed']];
    }
    
    $modeltask=new Task();
    $getleaderboard=$modeltask->getleaderboard();
?>
<div>
<div class="col-md-8">
      <div class=" panel panel-default">  
          <div class="panel-heading"><h3>Leader Board </h3></div>
    <div class="panel-body"><table class="table table-striped table-bordered">
        <tr><th>&nbsp</th><th>User</th><th>Open Task</th><th>Pages</th></tr>
        <?php foreach($getleaderboard as $row) { 
            
            echo "<tr><td>&nbsp</td><td>".$row['userfullname']."</td><td>".$row['count']."</td><td>".$row['pages']."</td></tr>";
        }
?>
        </table></div>
      </div>
</div>
    <div>
        <div class="panel panel-default col-md-4 pull-right">
    <div class="panel-body">
        <div id="container2"></div>
     </div>
</div>
<div class="row"></div>
<div class=" panel panel-default col-md-4 pull-right">
    <div class="panel-body">
        <div id="container1"></div>
    </div>
</div>
<div class="row"></div>
    </div>
</div>


<script>
    Highcharts.chart('container2', {
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie',
            options3d: {
                enabled: true,
                alpha: 45,
                beta: 0
            }
        },
         credits: {
              enabled: false
        },
        title: {
            text: 'Cases Closed'
        },
        credits: {
            enabled: false
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                depth: 35,
                dataLabels: {
                    enabled: false,
                    format: ' {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    },
                },
                showInLegend: true
            }
        },
        series: [{
            name: 'Cases Closed',
            colorByPoint: true,
            data: <?php echo json_encode($data_cases_closed) ?>
        }]
    });

    Highcharts.chart('container1', {
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie',
            options3d: {
                enabled: true,
                alpha: 45,
                beta: 0
            },
                //spacingTop: 0,
                //spacingBottom: 0,
                //spacingLeft: 0,
                //spacingRight: 0,
                //margin: [0, 100, 0, 0],
            
        },
       /* legend: {
                    enabled: true,
                    floating: true,
                    verticalAlign: 'middle',
                    align:'right',
                    layout: 'vertical',
                    //y: $(this).find('#container1').height()/4,
                },*/
         credits: {
              enabled: false
        },
        title: {
            text: 'Pages Closed'
        },
        credits: {
            enabled: false
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                depth: 35,
                size:'75%',
                dataLabels: {
                    enabled: false,
                    format: '{point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    },
                },
                
                showInLegend: true,
                
            }
        },
        series: [{
                name: 'Pages Closed',
                colorByPoint: true,
                data: <?php echo json_encode($data_pages_closed) ?>
        }]
    });
</script>
        	

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/home2.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-home2">

    <div class="jumbotron">
        <h1>Task Management System</h1>

        <p class="lead">You have successfully created your Task Management System.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

frontend/views/site/index.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */

$this->title = 'BSDT Tracker';
?>
<div class="site-index">
	<div class="text-center">
		<?= Html::a('Get started with BSDT', ['task/index'], ['class' => 'btn btn-success']);?>
	</div>
</div>
<div class="row">
    <?= $this->render('dashboard'); ?>
</div>   
<div class="row">
    <?= $this->render('dashboardgraph1'); ?>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

               <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>